# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s2:
      addresses: [10.101.10.10]
    enp0s3:
      dhcp: false
      addresses: [9.9.9.9/8]
      routes:
        - to: default
          via: 8.8.8.8
    enp0s4:
      addresses: [8.8.8.8]
    enp0s5:
      dhcp4: true
  version: 2
